version: '3.7'
networks:
  gloover_network:
    driver: bridge
services:
  gloover_ws:
    container_name: gloover_ws
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGODB_DATABASE: gloover_db
      MONGODB_USERNAME: gloover_user
      MONGODB_PASSWORD: password1
      MONGODB_HOSTNAME: mongo
    volumes:
      - .:/var/www
    links:
      - mongo
    networks:
      - gloover_network
  gloover_scraper:
    image: vimagick/scrapyd:py3
    container_name: gloover_scraper
    entrypoint: scrapyrt -p 9080 -i 0.0.0.0
    ports:
      - 9080
    volumes:
      - ./gloover_scraper:/usr/src/app
    working_dir: /usr/src/app/gloover_scraper
    networks:
      - gloover_network
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Secret
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
    networks:
      - gloover_network
volumes:
  mongo-data:
  mongo-configdb:
