version: '3.8'
services:
  gloover_ws:
    container_name: gloover_ws
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGODB_DATABASE: gloover_db
      MONGODB_USERNAME: gloover_user
      MONGODB_PASSWORD: password1
      MONGODB_HOSTNAME: mongo
    volumes:
      - .:/var/www
    links:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Secret
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
volumes:
  mongo-data:
  mongo-configdb: